version: '2'

services:
  lava-worker:
    container_name: lava-worker0
    hostname: worker0
    build:
      context: ./
      args:
        version: 2020.02
        server: "lava-server"
        extra_packages: "lava-coordinator"
    restart: always
    devices:
#     - /dev/kvm     # can be requested for qemu with hw accel
      - /dev/net/tun # needed for QEMU
    cap_add:
      - NET_ADMIN    # needed for QEMU
    volumes:
      - ./overlays/etc/lava-server/lava-coordinator/lava-coordinator.conf:/etc/lava-server/lava-coordinator/lava-coordinator.conf
