version: '2'

services:
  lava-worker:
    container_name: lava-worker0
    hostname: worker0
    build:
      context: ./
      args:
        version: 2022.11
        server: "lava-server"
    restart: always
    devices:
#     - /dev/kvm     # can be requested for qemu with hw accel
      - /dev/net/tun # needed for QEMU
    cap_add:
      - NET_ADMIN    # needed for QEMU
